
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: ecommerce
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1> 3-Tier App</h1>
      <button onclick="callBackend()">Call Backend</button>
      <p id="result"></p>

      <script>
        function callBackend() {
          fetch("/api")
            .then(res => res.text())
            .then(data => {
              document.getElementById("result").innerText = data;
            });
        }
      </script>
    </body>
    </html>